### PR TITLE
Added ChainExpression type

### PR DESCRIPTION
**Pull request by ethancrook99**
Added a new `ChainExpression` type to line up with how babelParser@7.11.0 handles optional chaining. I left `OptionalChainExpression` but marked it as deprecated for projects that use older babel versions.

Meant to fix [this issue](https://github.com/benjamn/ast-types/issues/383)

### CODE REVIEW

**Comment by ethancrook99** [comment]
@benjamn Can I get a review on this?

**Comment by ethancrook99** [comment]
@benjamn Sure, I'll get started on those changes!

**Comment by ethancrook99** [comment]
@benjamn When adding the `expression` field, do I add the `ChainElement` type label as a string inside a `def()`? Like this--
```  
def("ChainExpression")
    .bases("Expression")
    .build("object", "property", "computed", "optional")
    .field("optional", Boolean, defaults["true"])
    .field("expression", def("ChainElement"));
```

It seems like that's the pattern used for other types but I can't tell for sure. I pushed the changes, will you let me know if I missed something?

**Comment by ethancrook99** [comment]
@benjamn I changed the supertype of `CallExpression` and `MemberExpression` to `ChainElement`, but it's causing a lot of tests to fail because those two types are no longer a subtype of `Expression` and aren't related to `ExpressionKind`. Do you know of a way to resolve that conflict?

**Comment by info-bit** [comment]
Are you planning to merge this fix anytime soon? We're stuck with a yarn resolution for babel in the package to support react-docgen.

**Review by benjamn — APPROVED** [review]
@ethancrook99 Thanks for continuing to work on this, and sorry for leaving you to figure out the key insight about multiple inheritance. That's one of the reasons I built this whole `def` system in the first place, instead of using ordinary JS prototypal inheritance, since prototypes allow for only single inheritance (with good reason, of course, but you really want multiple inheritance, or something like traits, for an AST type system like this).

**Comment by ethancrook99** [comment]
Thanks for finishing that up and getting it merged!

**Pull request merged**
