### PR TITLE
Fix ClassProperty fb-harmony definition

### PR DESCRIPTION
**Pull request by gabelevi**
The key can also be a literal or an expression. Also, I don't see a good reason to have static in the build (not a big deal, can revert that part if you disagree)

### CODE REVIEW

**Comment by benjamn** [comment]
Wait, what happened to the `key` field?

**Comment by gabelevi** [comment]
It's defined in [`es6.js`](https://github.com/benjamn/ast-types/blob/c4d0280add526ebe38fa9698e056c8fe3fe8c639/def/es6.js#L141). The `fb-harmony.js` file is extending that core definition. This PR fixes a bug where we were actually making the `ClassProperty` node's key type more limited.

**Comment by benjamn** [comment]
Ah, right.

**Comment by benjamn** [comment]
https://github.com/benjamn/ast-types/releases/tag/v0.8.4

**Comment by gabelevi** [comment]
Thanks!

**Pull request merged**
