### PR TITLE
Fix await parenthesization when printing

### PR DESCRIPTION
**Pull request by skeggse**
Attempts to fix benjamn/recast#589.

### CODE REVIEW

**Comment by pentacular** [comment]
I'm running into this problem as well -- could this be reviewed?

**Comment by eventualbuddha** [comment]
@benjamn this seems reasonable to me. Want to give me Github + NPM access for ast-types too, or do you want to handle this?

**Comment by conartist6** [comment]
I'm moving to supplant this with https://github.com/benjamn/recast/pull/712/, which fixes the same issues. Of course it will still need a reviewer.

**Comment by skeggse** [comment]
Oh hey the replacement PR got merged! I can close this!

**Pull request closed without merging**
