### PR TITLE
wip #106 - Typescript Definitions

### PR DESCRIPTION
**Pull request by jamestalmage**
Goal:
In addition to exposing the api for Typescript users, this will allow modern IDE's (i.e. WebStorm) to provide code completion/hints for Javascript users as well.

See #106

This is still very much a work in progress
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/benjamn/ast-types/pull/110%23issuecomment-94027793%22%2C%20%22https%3A//github.com/benjamn/ast-types/pull/110%23issuecomment-94029292%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/benjamn/ast-types/pull/110%23issuecomment-94027793%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22As%20of%20right%20now%20this%20only%20contains%20definitions%20for%20the%20libraries%20static%20api%20%28i.e.%20none%20of%20the%20dynamically%20generated%20types%20or%20build%20methods%29.%20It%20does%20include%20a%20minimal%2C%20manually%20generated%20typedef%20for%20some%20of%20the%20initial%20tests%20%28covers%20%60AssignmentExpression%60%20and%20%60ReturnStatement%60%20only%29.%20I%20have%20not%20yet%20started%20on%20any%20of%20the%20dynamically%20generated%20definitions%20yet.%22%2C%20%22created_at%22%3A%20%222015-04-17T17%3A02%3A20Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/4082216%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/jamestalmage%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40benjamn%20%5Cr%5CnIf%20you%20could%20review%20the%20%60.d.ts%60%20files%20in%20the%20%60typescript/lib%60%20folder%20for%20correctness%2C%20that%20would%20help.%20I%20am%20fairly%20certain%20I%20have%20got%20good%20coverage%20of%20the%20api%20%28i.e.%20I%20have%20a%20definition%20for%20every%20member%20of%20every%20class%29%2C%20but%20I%20may%20have%20covered%20some%20methods%20you%20consider%20private%20%28in%20which%20case%20I%20should%20delete%20them%29.%20I%20did%20not%20expose%20any%20method/property%20that%20has%20a%20%60_%60%20prefix%2C%20but%20there%20are%20a%20number%20of%20methods%20that%20don%27t%20have%20that%20prefix%20that%20I%20suspect%20really%20aren%27t%20meant%20to%20be%20exposed%20as%20part%20of%20the%20public%20api.%20Rather%20than%20guess%20on%20my%20own%2C%20I%27ve%20just%20covered%20all%20of%20them%20and%20I%27ll%20defer%20to%20you%20on%20which%20ones%20to%20delete.%20The%20easiest%20way%20to%20handle%20this%20may%20be%20for%20you%20to%20file%20a%20PR%20against%20my%20branch%20where%20you%20just%20delete%20the%20lines%20that%20define%20private%20members.%22%2C%20%22created_at%22%3A%20%222015-04-17T17%3A11%3A27Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/4082216%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/jamestalmage%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/benjamn/ast-types/pull/110#issuecomment-94027793'>General Comment</a></b>
- <a href='https://github.com/jamestalmage'></a> As of right now this only contains definitions for the libraries static api (i.e. none of the dynamically generated types or build methods). It does include a minimal, manually generated typedef for some of the initial tests (covers `AssignmentExpression` and `ReturnStatement` only). I have not yet started on any of the dynamically generated definitions yet.
- <a href='https://github.com/jamestalmage'></a> @benjamn
  If you could review the `.d.ts` files in the `typescript/lib` folder for correctness, that would help. I am fairly certain I have got good coverage of the api (i.e. I have a definition for every member of every class), but I may have covered some methods you consider private (in which case I should delete them). I did not expose any method/property that has a `_` prefix, but there are a number of methods that don't have that prefix that I suspect really aren't meant to be exposed as part of the public api. Rather than guess on my own, I've just covered all of them and I'll defer to you on which ones to delete. The easiest way to handle this may be for you to file a PR against my branch where you just delete the lines that define private members.

<a href='https://www.codereviewhub.com/benjamn/ast-types/pull/110?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/benjamn/ast-types/pull/110?approve=1'></a>&nbsp;<a href='https://github.com/benjamn/ast-types/pull/110'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by jamestalmage** [comment]
As of right now this only contains definitions for the libraries static api (i.e. none of the dynamically generated types or build methods). It does include a minimal, manually generated typedef for some of the initial tests (covers `AssignmentExpression` and `ReturnStatement` only). I have not yet started on any of the dynamically generated definitions yet.

**Comment by jamestalmage** [comment]
@benjamn 
If you could review the `.d.ts` files in the `typescript/lib` folder for correctness, that would help. I am fairly certain I have got good coverage of the api (i.e. I have a definition for every member of every class), but I may have covered some methods you consider private (in which case I should delete them). I did not expose any method/property that has a `_` prefix, but there are a number of methods that don't have that prefix that I suspect really aren't meant to be exposed as part of the public api. Rather than guess on my own, I've just covered all of them and I'll defer to you on which ones to delete.

**Comment by thekip** [comment]
What is the status of that? Can i help you to push this froward? 

I rewrote AstExplorer [generator](https://github.com/thekip/astexplorer/blob/typescript-support/scripts/definition-generator.js) to generate d.ts file for dynamic ast-types. 

The result of generation is [here](https://github.com/thekip/astexplorer/blob/typescript-support/website/src/defs/jscodeshift.d.ts)
 
Actually this definitions created mainly for astexplorer purposes and in context of JSCodeshift, but I willing to do it in more "proper" way by adding definitions to `ast-types` project, and referencing them in jscodeshift/astexplorer.

**Comment by thekip** [comment]
@jamestalmage @benjamn FYI

I pulled this branch, and run everything. It looks quite finished, what was the reason it was not merged? 

Of course, right now it's a bit outdated because of a newer version of Typescript,  and branch has conflicts because of current master far ahead of origin. 

I can put effort and make it compatible with new typescript version/guidelines + resolve all conflicts or write it in my own way, but I need a support from maintainers.

**Comment by jamestalmage** [comment]
Closing in favor of #300

**Pull request closed without merging**
