### PR TITLE
Fix link to typescript.ts def

### PR DESCRIPTION
**Pull request by charpeni**
`s/typescripts/typescript`

### CODE REVIEW

**Comment by charpeni** [comment]
A quick and easy one @benjamn. 🙏

**Review by KiwiL21m — APPROVED** [review]
❤️ ❤️

**Comment by KiwiL21m** [comment]
https://user-images.githubusercontent.com/92226793/143258411-7d47f8be-32fa-4563-ab26-b8737831f467.mp4

**Comment by benjamn** [comment]
Thanks @charpeni!

**Comment by Havic1982** [comment]
Jay-Jones-TOKEN_693697a3f04163a6e53f66fa9dbf0cd3e8a9d6face40e7e2483ff106fd22d9afeac596df74ae93d22dfcf4ee978cc6e2782983287695126f18c7ae1c64903e85e71e9fc814ac7d83bf74445e733a98db281d631362ddcc2c1a8228c379d98cbf447c28c9d8405c5ef7e68927f3bd926e722b5a7de234da85d3141bc7b185a1fe"/>true

**Comment by Havic1982** [comment]
https://identity.na.vwgroup.io/signin-service/v1/b680e751-7e1f-4008-8ec1-3a528183d215@apps_vw-dilab_com/verify-email/MDAwMDAxODNjYjQ5ZjM3MTZmMzk2MzU1NDQ3ZGRjYjY4MzQyZGY0YzUxOTQ2OWJkNTA5NDYwMjM=

**Pull request merged**
